Ensembl/VEP_plugins

ExAC.pm

Added non mandatory arguments for AN,AC display. Corrected AN display to now show AN_adj for reference allele counts.

AN,AC display non mandatory arguments + AN_adj counts

---

Downstream.pm
dbNSFP.pm

This involves a simple doc fix I mentioned in Issue #18, plus fixing a bug in Downstream.pm.

Bug fixes for dbNSFP and Downstream

---

plugin_config.txt

Fixes #26. Feel free to reject if this is not intended to happen yet.

Change plugin URLs to point at release 85

---

AncestralAllele.pm
plugin_config.txt

retrieves ancestral alleles for input variants from FASTA file

AncestralAllele plugin

---

Downstream.pm
LOVD.pm
SameCodon.pm
miRNA.pm

Update NAME to match module name

Correction to NAME in perldoc

---

MTR.pm

Please await review by @silkm and addition of path to data file before merge

add MTR plugin

---

Downstream.pm

I will send another PR for  postreleasefix/92

Fix computation of last complete codon

---

dbNSFP.pm

The newest version of dbNSFP support GRCh37 annotation. However we need to index differently to support GRCh37 coordinates. I also added instructions for users for how to index if they want to use v3.5c for GRCh37.
Probably too late to include for rest and vep tool for 92. But I will ask the web team.

support dbNSFP v3.5c for GRCh37

---

dbNSFP.pm

https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-1114

use M for MT because dbNSFP calls the mitochondria M

---

REVEL.pm

Added tabix processing instructions to REVEL plugin

Added tabix processing instructions to REVEL plugin

---

G2P.pm

In response to issue reported [here](https://github.com/Ensembl/ensembl-vep/issues/228)

remove CGI dependency

---

G2P.pm

Some last minute updates. Mostly feedback from latest G2P meeting and changes for dealing with refseq transcripts.

integrate feedback from latest meeting

---

G2P.pm

Add changes as discussed in #86 to 94 branch

add feedback from latest G2P meeting

---

G2P.pm

Fix 2 bugs which I just spotted. I will send another PR for postreleasefix/94.

fix 2 bugs

---

Phenotypes.pm

Update to use correct output format flag

fix verbose json format

---

dbNSFP.pm

Removed dbNSFP filename from error message preventing concat issue

---

MaxEntScan.pm

Hi, we have added two new modules to the MaxEntScan plugin. We've called these the SWA (sliding window approach) and the NCSS (nearest canonical splice site) modules. We've added a description on how these work in the header of the plugin. We have found the scores very useful for our analysis of variants and think that they would be useful for others. Please let me know if you have any questions or suggestions.

SWA and NCSS modules for MaxEntScan

---

G2P.pm

Added changes which consider if Bio::DB::HTS::Tabix is installed. Emily has problems to install it on her laptop and reported some problems with the G2P plugin. I also fixed a few other minor bugs. I have some restructuring plans for release/95 which is why I'm not going to submit anything to postreleasefix/95 just now.

check if Bio::DB::HTS::Tabix is installed

---

TSSDistance.pm

fix description of usage of TSSDistance plugin

---

G2P.pm

Check at compile time if Bio::DB::HTS::Tabix is properly installed

check module availability at compile time

---

G2P.pm

Addresses bug pointed out by Ensembl/ensembl-vep#247

don't remove any directories

---

G2P.pm

- Don't remove log directories
- Check if we can use Bio::DB::HTS::Tabix
- some typo bug fixes

accumulation of bug fixes

---

CADD.pm

Address https://github.com/Ensembl/VEP_plugins/issues/14#issuecomment-440597076
Don't trim first letter of indels and use get_matched_variant_alleles.

 improve indel annotation

---

CADD.pm

Add PR from https://github.com/Ensembl/VEP_plugins/pull/118 to release/95

Don't trim first letter of indels and use get_matched_variant_alleles.

---

POSTGAP.pm

Same as #104 now for release/95.

New plugin

---

G2P.pm

Same as https://github.com/Ensembl/VEP_plugins/pull/120 now also for release/95.

add more checks to ensure frequency annotation works

---

dbNSFP.pm

Same as https://github.com/Ensembl/VEP_plugins/pull/143 but now for master and release/96

check version when match coords from header

---

Phenotypes.pm

- report unique results
- add phenotype_feature option : reports `phenotype description`, `object id` and `source`
- fix filter bug

updates to Phenotypes plugin

---

Conservation.pm

Same updates as https://github.com/Ensembl/VEP_plugins/pull/139/files

Conservation Updates

---

NearestExonJB.pm

Plugin to report nearest exon junction boundary for variants in the protein coding region.
Reports:
- exon identifier
- bp distance
- start /end if it's nearest to the start/end of the exon
- exon bp lenght

add plugin nearest exon junction boundary

---

ProteinSeqs.pm

Update to proteinseqs to prevent a warning

---

PostGAP.pm

release 96 fix : https://github.com/Ensembl/VEP_plugins/pull/174

fix fetch position PostGAP

---

Phenotypes.pm
plugin_config.txt

- output file is 1-based GVF not BED
- coordinates for insertions are start < end

Fix insertion

---

PostGAP.pm

copy of master PR https://github.com/Ensembl/VEP_plugins/pull/18

standardize coords processing -e97

---

StructuralVariantOverlap.pm

Similar to ExAC plugin but for SVs - reports frequencies and other INFO from overlapping variants in  reference VCF but finds configurable non-exact overlaps

 initial SV VCF overlap plugin 

---

G2P.pm

Same as https://github.com/Ensembl/VEP_plugins/pull/196 but now for master and release/98

update default selections and bugfix

---

Phenotypes.pm

Copy of Emily's PR (https://github.com/Ensembl/VEP_plugins/pull/201) for the release 98

Update Phenotypes plugin documentation

---

Mastermind.pm
ReferenceQuality.pm

Fix issue - experimental keys on scalar 

---

Mastermind.pm
ReferenceQuality.pm

Fix experimental keys on scalar

---

G2P.pm

Bugfix for https://github.com/Ensembl/VEP_plugins/issues/200

remove experimental keys on scalar

---

G2P.pm

Will fix https://github.com/Ensembl/ensembl-vep/issues/527

store file for later

---

G2P.pm

2 recent bug fixes which have been separately committed against release/97

commit recent bug fixes

---

Mastermind.pm

Fix for #212 
Unable to find synonyms for for chr on GRCh37

Looks up synonym by removing chr if no synonym found

---

LD.pm

This will include EUR as valid population for LD calculation. https://github.com/Ensembl/VEP_plugins/issues/141

add super populations to list of valid populations

---

CADD.pm

Provide more documentation on which input files are supported.

add documentation on supported input files

---

Mastermind.pm

Fix verification of non-numeric values for UTR variants (issue #217) 
Fix frameshifts  
Fix ref and alt alleles comparison

Mastermind - fix non numeric verification and other bugs

---

Mastermind.pm

Mastermind e98 - fix non-numeric values, alleles verification and other bugs

---

G2P.pm

same as https://github.com/Ensembl/VEP_plugins/pull/218

af_from_vcf option cannot be run in offline mode

---

plugin_config.txt

for plugin in PR: https://github.com/Ensembl/VEP_plugins/pull/213

add satMutMPRA plugin to plugin_config

---

G2P.pm

This is all been updated for 97 before and tested.

run in offline mode with af_from_vcf

---

G2P.pm

Add option to set confidence levels rather than using the default confidence levels.

flexible choice of confidence levels

---

StructuralVariantOverlap.pm

Addresses 2-5 from #229. Slight docs improvement for 6

SV updates - add label, reciprocal match, docs, type fix

---

G2P.pm

Catch any problems during log directory creation.

catch errors during log_dir creation

---

LocalID.pm

PR to fix  issue #255 for postreleasefix/99.
See   PR for release/98  #256

LocalID plugin warns if id not found

---

SpliceAI.pm

Old PR here: https://github.com/Ensembl/VEP_plugins/pull/270

New plugin SpliceAI - predict effect on splicing (99) 

---

Mastermind.pm

Mastermind - check peptide end position

---

StructuralVariantOverlap.pm

Fix SV overlap custom field 100

---

DisGeNET.pm

DisGeNET file: https://www.disgenet.org/static/disgenet_ap1/files/downloads/all_variant_disease_pmid_associations.tsv.gz

New plugin DisGeNET Variant-Disease-PMID associations

---

CADD.pm
RefSeqHGVS.pm
dbNSFP.pm
satMutMPRA.pm

Update citations for dbNSFP

---

StructuralVariantOverlap.pm

SV overlap 

---

G2P.pm

Add whitelist option to skip frequency filter if variant is on whitelist. I added test data here: [PATH_TO_PANDA]/G2P/whitelist_pr_14042020/:
--vep_g2p_38_100_no_whitelist.sh
--vep_g2p_38_100_whitelist.sh
I can present a code review next Monday. The plan is to get it in for release 100 and then create PRs against postreleasefix/101 too.

Vep g2p100/whitelist

---

StructuralVariantOverlap.pm

SV Overlap can't read 'chr' from reference file

---

StructuralVariantOverlap.pm

SV Overlap can't read 'chr' from reference file e101

---

DisGeNET.pm

Old instructions don't work with the current file from DisGeNET https://www.disgenet.org/static/disgenet_ap1/files/downloads/all_variant_disease_pmid_associations.tsv.gz

DisGeNET fix instructions

---

DisGeNET.pm

DisGeNET fix instructions 101

---

AncestralAllele.pm

Update fasta file location
Add module for throwing errors
See ENSVAR-3336
PR for e101.
PR will be made for e102 when merged

Fix AncestralAllele plugin docs and module used

---

NearestGene.pm

Update docs and offline check.
See ENSVAR-3335
Separate PR will be made for e102

Fix NearestGene 

---

CADD.pm

same as https://github.com/Ensembl/VEP_plugins/pull/316, now on postreleasefix/102

Fix - CADD -1 strand

---

dbNSFP.pm

Same as https://github.com/Ensembl/VEP_plugins/pull/314

support different 4.x versions

---

G2P.pm

Option added for release/100 was missing from release/101 branch.

add variant include list option

---

SpliceAI.pm

Fix SpliceAI instruction 101

---

neXtProt.pm
neXtProt_headers.txt

Add new plugin neXtProt

---

SpliceAI.pm

Fix SpliceAI instructions

---

G2P.pm

add latest gnomADg_r3.0 key

---

PolyPhen_SIFT.pm

Restrict analysis to PolyPhen and SIFT - e101

---

neXtProt.pm

PR to fix the URL provided by the query.

Fix neXtProt url

---

Mastermind.pm

Update mastermind 101

---

Mastermind.pm

Update Mastermind 102

---

dbNSFP.pm

support newer version 4 of dbNSFP

---

PolyPhen_SIFT.pm

Also remove download link
Same as #330
For e102, to be be merged into release/102 and master

Restrict analysis to PolyPhen and SIFT - e102

---

neXtProt.pm
neXtProt_headers.txt

Add new plugin neXtProt 102

---

plugin_config.txt

Update plugin url with new release version before branch.

release 103 update

---

DisGeNET.pm
plugin_config.txt

This PR is to address comments from https://github.com/Ensembl/public-plugins/pull/366 
Same as PR #354

Fix DisGeNET 102

---

neXtProt.pm

Fix compilation error in neXtProt plugin for perl v5.26.1 (103) 

---

neXtProt.pm

Add consequence stop_gain to neXtProt (103) 

---

Mastermind.pm

ENSVAR-3579
To keep the current Mastermind workflow, the new option is also a value '1'. 
Examples to use the new option:
```
--plugin Mastermind,/path_to_file/mastermind_file.vcf.gz,0,1
--plugin Mastermind,/path_to_file/mastermind_file.vcf.gz,1,1
```

Add new option to Mastermind 

---

plugin_config.txt

Add a description to be displayed in VEP input form for release 103. 
Change 'Phenotype data' to 'Phenotype data and citations' http://ves-hx2-76.ebi.ac.uk:7040/Homo_sapiens/Tools/VEP?db=core;tl=yPaDAdUxd9Wfh2ll-303

Mastermind description 

---

neXtProt.pm
neXtProt_headers.txt

1) Update query with additional annotations.
2) Update the header file. 
ENSVAR-3611

Update neXtProt 

---

Mastermind.pm

User suggested returning the Mastermind URL - return as an option.

Mastermind add option to return URL

---

dbNSFP.pm

See ENSVAR-3617
Similar PR will be made for 103

Add documentation for dbNSFP 4.1a

---

dbNSFP.pm

Documentation updates as done for e102 #364

Docs for 4.1a and use of temp sort directory

---

gnomADc.pm

This PR adds support for the recent gnomAD release 3.0, but also for the less recent release 2.1. Previously, we needed to download and Tabix index one coverage file per chromosome. In these last two releases, we now have only one coverage file to download. So I've updated the plugin to handle the new format. It should also handle directory input like before.
Also, the latest release (r3.0 for GRCh38) has a new 'locus' field that combines the 'chrom' and 'pos' fields. This is a little inconvenient as it means we now need to pre-process the file so that it can be Tabix-indexed. Not sure if there's any other way around this.

Update gnomADc.pm for releases 2.1 and 3.0

---

plugin_config.txt

Needs to be merged into master and release/104

update to release 104

---

G2P.pm

This is a fix for the bug reported here https://github.com/Ensembl/VEP_plugins/issues/373
Test data and a script for running the plugin is here PANDA/G2P/gene_symbol_panelapp_pr_05012021
When the PR has been reviewed I will also create PRs for the following release branches until the most recent.

store gene symbol from panelall input

---

G2P.pm

Same as #375 for release/101 branch

store gene symbol from panelapp input

---

REVEL.pm

same as https://github.com/Ensembl/VEP_plugins/pull/374 (e103) now for -e104

REVEL - update docs for grch37/grch38 

---

Mastermind.pm

1. use add_file to populate $self->{_files}
2. update Mastermind_MMID3 description to display on web vep 
ENSVAR-3549

Fix mastermind - add input file

---

Mastermind.pm

Fix mastermind - add input file (104)

---

G2P.pm

Issue with link to summary page reported by user https://github.com/Ensembl/VEP_plugins/issues/373

G2P - fix url

---

dbNSFP.pm

PR for #382
For further details and examples see: ENSVAR-3930

Add pep match to dbNSFP plugin

---

G2P.pm

use ensembl assigned stable_id

---

G2P.pm

use new sub to get gene_symbol_id

---

ClinPred.pm
plugin_config.txt

The Clinpred plugin 
ENSVAR-2601

The ClinPred plugin

---

DisGeNET.pm
MTR.pm
Mastermind.pm
SpliceAI.pm

Removing duplication of the add_file() methods in this plugin.
ENSVAR-4101

Add file remove duplication

---

G2P.pm

Fixing the check for if the log_directory is empty.
ENSVAR-4111

Check for if the log_directory is empty

---

FATHMM_MKL.pm
MPC.pm
MTR.pm
PON_P2.pm
REVEL.pm
dbNSFP.pm
dbscSNV.pm

ENSVAR-4100
Changing the numeric comparison operator from "eq" to ==

Use of == for numeric comparisons

---

gnomADc.pm

Testing files can be found here : /nfs/production/panda/ensembl/variation/data/gnomADc

Updating the documentation of the plugin

---

dbNSFP.pm

Fix for e105 see related PR #429

dbNSFP fix for multi-allelic and peptide matching

---

NMD.pm
plugin_config.txt

NMD_escaping_variants_plugin

---

plugin_config.txt

Form is necessary for web interface.
ENSVAR-4366

Spliceai add form 

---

G2P.pm

Updating allelic requirement and confidence category

---

Mastermind.pm

Same as https://github.com/Ensembl/VEP_plugins/pull/436

Mastermind - match multi allelic variants with pep_match (e105)

---

Mastermind.pm

Issue reported for dbNSFP: ENSVAR-4336
This PR replaces https://github.com/Ensembl/VEP_plugins/pull/436

Mastermind - match multi allelic variants with pep_match (e106)

---

IntAct.pm
plugin_config.txt

Test data can be found with related JIRA ticket -
[ENSVAR-3250](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-3250)

Addition of IntAct plugin

---

gnomADc.pm
plugin_config.txt

https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4578
For testing : Files can be found in /nfs/production/flicek/ensembl/variation/data/gnomADc/

Gnomadv3.1 changes

---

neXtProt.pm
plugin_config.txt

Added requires data flag in plugin config and updated text in plugin module as per: https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4535

updating neXtProt

---

SameCodon.pm

[ENSVAR-4733](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4733) #475

Adding documentation for SameCodon

---

plugin_config.txt

[JIRA Card](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4724)
This PR is meant to add new dbNSFP version + update respective README file.
1) Run `vep` with new reference file.

feat: add new dbnsfp file + update readme

---

plugin_config.txt

The dbNSFP version was first updated in this PR: https://github.com/Ensembl/VEP_plugins/pull/484
However, another PR reverted the updates ([PR](https://github.com/Ensembl/VEP_plugins/pull/487))

Update dbNSFP version (4.3)

---

CONTRIBUTING.md

Renaming master to main for files dependent on ensembl-variation repo

Renaming master to main for ensembl-variation

---

REVEL.pm

[ENSVAR-4805](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4805)
#496

Updating the Revel docs

---

plugin_config.txt

NMD transcript will be available in web VEP in e107. It will be available under "Transcript annotation" section

Update NMD plugin section for web VEP

---

G2P.pm

[ENSVAR-4769](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4769)

Changes to G2P to support HGNC

---

MTR.pm

Addresses https://github.com/Ensembl/VEP_plugins/issues/509

check Genomic_position header is present at startup

---

G2P.pm

[ENSVAR-4554](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4554) The changes due to the keys changing and also contains changes from [ENSVAR-4835](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4835)

Changes to the keys due to vcf_config.json

---

G2P.pm

G2P Supporting all the allelic requirements we have

G2P Supporting more allelic requirements

---

G2P.pm

[ENSVAR-5005](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5005)

Changes to support panelapp

---

Mastermind.pm

Details: [ENSVAR-4453](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4453)

Mastermind nonsense variants

---

Mastermind.pm

[ENSVAR-5137](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5137)

Mastermind update documentation

---

NMD.pm

NMD now supports other consequence (stop gained, frameshift, splice acceptor and splice_donor)

NMD - Changes to the documentation

---

mutfunc.pm

example CLI command - 
```
PLENV_VERSION=5.14.4 perl /hps/software/users/ensembl/repositories/snhossain/ensembl-vep/vep --i ../data/motif_test --o ../output/test_result.txt --offline --fork 2 --dir_cache /nfs/production/flicek/ensembl/variation/data/VEP/tabixconverted --cache_version 106 --assembly GRCh38 --fasta /nfs/production/flicek/ensembl/variation/data/Homo_sapiens.GRCh38.dna.toplevel.fa.gz --force_overwrite --hgvs --plugin mutfunc,db=./mutfunc_data.db,int=1,motif=1,extended=1
```
example REST url - http://wp-np2-11.ebi.ac.uk:7075/vep/human/hgvs/P54259:p.S103A?content-type=application/json&mutfunc=1

Outputting all field as default behavior

---

mutfunc.pm

For single VEP process the following condition is false and thus not creating db connection - 
https://github.com/nakib103/VEP_plugins/blob/222d0020cedcc64c4ccc7601a6a2383e478ad87c/mutfunc.pm#L262
Thus we need to create db connection in the `new` function.

Fix issue when running with no-fork

---

UTRAnnotator.pm
plugin_config.txt

Just a cherry-pick to release 108 since 109 branch already exists and have other alterations.

hotfix: Cherry pick UTRAnnotator to release 108

---

SpliceAI.pm

Hi,
I believe this is a decent fix for  #538 .
Not sure if my PR is against the correct branch though. Please let me know if something is wrong or unclear.
Regards,
Nicolas

make sure gene names match even if SpliceAI file has a single gene name

---

AncestralAllele.pm
ProteinSeqs.pm

[ENSVAR-5203](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5203)
[ENSVAR-5200](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5200)

AA and ProteinSeqs - Improvement 

---

SpliceAI.pm

[ENSVAR-5215](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5215)

SpliceAI remove reverse_comp

---

G2P.pm

G2P - changes to improve efficiency

---

REVEL.pm

[ENSVAR-5217](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5217)

REVEL plugin - Transcript check 

---

G2P.pm

[ENSVAR-3959](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-3959)

Adding mane option to G2P plugin

---

GWAS.pm
plugin_config.txt

Adding new plugin - GWAS. Currently only supports CLI.
GWAS data file can be found in - `/nfs/production/flicek/ensembl/variation/data`
Example command - 
```
PLENV_VERSION="5.14.4" perl $homedir/ensembl-vep/vep \
--force_overwrite \
--i test.vcf \
--o $output_dir/test_out.vcf \
--species homo_sapiens \
--fork 4 \
--cache_version 108 \
--assembly GRCh38 \
--cache $cachedir \
--vcf \
--fasta $fasta_file \
--plugin GWAS,file=$data_dir/GWAS/gwas_catalog_v1.0.2-associations_e107_r2022-09-14.tsv
```
or if you want to test summary stats give 
```
--plugin GWAS,type=sstate,file=$data_dir/GWAS/17463246-GCST000028-EFO_0001360.h.tsv.sorted.gz
```
example input - 
for curated file
```
7	95125673	.	G	A	.	.
7	95125673	.	G	T	.	.
6	28005587	.	C	A	.	.	
11	117110070	.	G	C	.	.
1	204190659	.	G	A	.	.
1 …
```

Add new plugin - GWAS

---

LOEUF.pm

Details: [ENSVAR-4317](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4317)

LOEUF support GRCh38

---

plugin_config.txt

Update versions from `109` to `110`.
Last PR example:
https://github.com/Ensembl/VEP_plugins/pull/531

feat: Update plugin release versions e110

---

plugin_config.txt

[ENSVAR-5415](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5415)
tested in sandbox - http://wp-np2-11.ebi.ac.uk:7070/Homo_sapiens/Tools/VEP/Results?tl=eFJILrxFAnmC3CEJ-134

Remove extended option from mutfunc in web VEP

---

UTRAnnotator.pm

Small fixes to better support header view in web.
Wait for sandbox.

refactor: smaller header info for UTRAnnotator

---

MTR.pm

Issue: https://github.com/Ensembl/VEP_plugins/issues/589

Minor fix to search Genomic position in header

---

NMD.pm

Reverse strand consideration is for only the penultimate exon check. 
#568

nmd reverse transcript check 

---

CADD.pm

Document CADD_SV updates from -
https://github.com/Ensembl/VEP_plugins/pull/566

Update help docs for CADD_SV

---

G2P.pm

[ENSVAR-5523](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5523)

G2P -Changes to the variation_feature_seq

---

FATHMM.pm
PON_P2.pm
config/ubuntu-packages.txt

related to - https://github.com/Ensembl/ensembl-vep/pull/1464

Update docker dependencies for latest ubuntu LTS

---

AlphaMissense.pm
plugin_config.txt

Add AlphaMissense plugin (110)

---

AlphaMissense.pm
plugin_config.txt

Add AlphaMissense plugin (111)

---

GO.pm

* Allow to input a custom GFF filename with GO terms
* Improve formatting of GO term results in REST and JSON output: test in my [sandbox](http://wp-np2-11.ebi.ac.uk:9300/vep/human/region/12:40340400-40340400:1/A?GO=1&content-type=application/json)
* Improve error messages
* Match GO terms based on:
- Gene ID (`--plugin GO,match=gene`)
- Gene symbol (`--plugin GO,match=gene_symbol`)

GO plugin improvements

---

DosageSensitivity.pm
plugin_config.txt

[ENSVAR-5484](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5484)
```
vep --id '1 230685659 . T <CNV1> . . END=230806671' --database --force --plugin DosageSensitivity,file=/pathto/Collins_rCNV_2022.dosage_sensitivity_scores.tsv.gz,cover=1
vep --id 'rs699' --database --force --plugin DosageSensitivity,file=/pathto/Collins_rCNV_2022.dosage_sensitivity_scores.tsv.gz
vep --id 'rs699' --database --force --plugin DosageSensitivity,file=/pathto/Collins_rCNV_2022.dosage_sensitivity_scores.tsv.gz,cover=1
```

Dosage Sensitivity plugin

---

plugin_config.txt

Update DosageSensitivity plugin section to `Pathogenicity predictions`

Update DosageSensitivity plugin config

---

FATHMM_MKL.pm

Issue reported here: https://github.com/Ensembl/VEP_plugins/issues/676
The fix should also be included in release/111

Fix  FATHMM_MKL

---

PhenotypeOrthologous.pm
plugin_config.txt

[ENSVAR-4837](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4837)

Vep plugin phenotype orthologous

---

PhenotypeOrthologous.pm

[ENSVAR-4837](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4837)
Making fixes to the Orthologous plugin

Updating pheno orthologous

---

ProteinSeqs.pm

[ENSVAR-5920](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5920)
```
vep -i input --shift_hgvs 0 --force_overwrite --assembly GRCh37 --database  --hgvs --plugin ProteinSeqs,output.reference.fa,output.mutated.fa
```
```
1   955552  .   CATG    C
1   990358  .   ATGA    A
1   990360  .   GA  G
1   990361  .   GA  G
2   217498305   .   T   TGCTGCC
4   40434704    .   AGCGGCTGCGGCGGCTGCGGCC  A
6   41754573    .   C   CCTT
6   43250725    .   GGAA    G
```

Handling deletion in alt protein sequence

---

neXtProt.pm

neXtProt documentation and check

---

plugin_config.txt

ENSVAR-6096: Move DosageSensitivity, LOEUF and pLI to new section `Gene tolerance to change`
Web VEP changes: https://github.com/Ensembl/public-plugins/pull/769

Add new plugin section `Gene tolerance to change`

---

plugin_config.txt

Currently not visible on documentation - adding to variant data category

Adding denovo to visible list

---

AlphaMissense.pm
plugin_config.txt

[ENSVAR-6261](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6261)

Update AlphaMissense for web VEP

---

AlphaMissense.pm

AlphaMissense: improve JSON output

---

AVADA.pm
plugin_config.txt

Ticket: [ENSVAR-4997](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4997)
```
1   949523  .   C   T
1   957605  .   G   A,T,C
1   949739  .   G   T
X   154509348   .   G   T
```

Plugin support for AVADA

---

StructuralVariantOverlap.pm

[ENSVAR-6270](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6270)

Modified order to fetch chr before seq_region_name

---

UTRAnnotator.pm

Updated terms to comply with new SO terms - see ENSVAR-6287

UTRanno term changes

---

AVADA.pm
GeneBe.pm

Related with https://github.com/Ensembl/public-plugins/pull/790

Fix VEP plugin docs

---

CADD.pm

ENSVAR-6259 - CADD plugin 

---

ClinPred.pm

[ENSVAR-6364](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6364)
#719

Adding support for ClinPred GRCh38

---

REVEL.pm

ENSVAR-6396
Related with https://github.com/Ensembl/public-plugins/pull/806 and https://github.com/Ensembl/ebi-plugins/pull/175

REVEL plugin: set human assembly for web VEP

---

dbNSFP.pm
plugin_config.txt

Update dbNSFP data to 4.8c and 4.9c

---

G2P.pm

Ticket: [G2P-193](https://www.ebi.ac.uk/panda/jira/browse/G2P-193)
Details about the test can be found in the ticket.
This PR fixes the issue reported here https://github.com/Ensembl/ensembl-vep/issues/1746

Update G2P - PanelApp allelic requeriment

---

Mastermind.pm

**Input to test**
`11      108200944       .       C       A       .              .              .`
Assembly: GRC37

Fix warnings in Mastermind

---

G2P.pm

[G2P-452](https://www.ebi.ac.uk/panda/jira/browse/G2P-452)

Update G2P plugin (G2P-452)

---

dbNSFP.pm

Modifying the plugin CLI help text to reflect v5.0 onwards changes to dbNSFP.

dbNSFP help text update

---

BayesDel.pm

#783 
- Removing an unused API call that throws a warning

Changes to BayesDel

---

G2P.pm

Update G2P - changes to stop the warning

---

plugin_config.txt

[ENSVAR-6855](https://embl.atlassian.net/browse/ENSVAR-6855)
Add CADD config for chicken red jungle fowl.

Add chicken rjf CADD config
