MaxEntScan.pm
Return empty hashref, not undef, if if bailing out. Otherwise lines are incorrectly filtered.
=> fix empty return statement

dbNSFP.pm
Clinvar fields returned from dbnsfp can contain | symbols, which conflicts with the | separator already used to separate fields by VEP.
This change replaces |s with &s.
This resolves https://github.com/Ensembl/VEP_plugins/issues/6
=> change dbnsfp separator to &

dbNSFP.pm
When the user is using dbNSFP version 2.9.1, there might be a file called "search_dbNSFP291.readme.pdf" which causes the plugin to parse the pdf file instead of the correct file.
=> Fix dbNSFP parse the wrong readme file

dbNSFP.pm
For an older version of dbNSFP, the column name for position is 'pos(1-coor)' not 'pos(1-based)'.
=> Add special case for dbNSFP version 2.9.1

NearestGene.pm
NearestGene plugin doesn't work neither inside docker container provided.
This is my fix, I don't know Perl and VEP code but I hope that be useful.
Regards.
=> NearestGene: Fix "ERROR: Could not get gene adaptor"

SubsetVCF.pm
This is a plugin designed to report the INFO fields of a VCF for all overlapping variants. While the behaviour is similar to using the custom flag, it differs in that INFO values for all alleles are returned (along with all alleles and original REF / POS values). Matching alleles are re-oriented to be concordant with those being output by VEP (non-matching are left as-is). Additionally, users can specify to only report variants marked as PASS. To facilitate ease of use, users can use `*` as a wildcard to help specify which info fields to report.
=> Adding SubsetVCF

dbNSFP.pm
following Emily's recommendation to get rid of old installation instructions ([Ensembl #279900] Problem using VEP plugin dbNSFP)
=> Update installation instructions for version 3.5a

G2P.pm
Don't remove log directories. Addresses bug pointed out by https://github.com/Ensembl/ensembl-vep/issues/247
Will be fixed on release/94, 95 separately.
=> don't remove any directories

G2P.pm
This is tested with an installation where Bio::DB::HTS is not working. We also need to check if the existing VF has an empty array for the key named: existing. PR for release/95 is coming too.
=> add more checks to ensure frequency annotation works

LD.pm
Changes for #125 The plugin can take more than one population as argument. Add some code for backwards compatibility. If only one population is used use the same results key (LinkedVariants) as before. I also updated the caching of already computed results.
Some test data is under our panda variation space: variation/data/VEP_plugins/
=> calculate for more than one population

dbNSFP.pm
dbNSFP 4.0 changed their header line slightly. We now need to check for dbNSFP version to correctly assign coords.
=> check version when match coords from header

G2P.pm
The plugin is still trying to get extra allele frequencies from VCF through database connections. For very large input data this can cause connection problems. I added a reconnect when lost to hopefully prevent the lost connection errors. For release/97 I'm trying to use our VCF backend code to get rid of the db connection but still get allele frequency annotations for UK10K, TOPmed and gnomAD genomes.
=> reconnect when lost, replace undef value

G2P.pm
The core API doesn't seem to agree well with the capitalisation of VCFCollection. I still need to do more testing and suspect it is a perl 5.26 related issue.
=> fix issue with capitalisation

G2P.pm
G2P can be run in offline mode but only use annotations from cache files then. af_from_vcf option which allows to get annotations from additional VCF files doesn't work in offline mode. First of all because it it needs the VCFCollectionAdaptor from a registry object which I cannot get in offline mode. Same PR is coming for postreleasefix/98.
=> af_from_vcf option cannot be run in offline mode

CADD.pm
Fix for https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-2365
Problem was that the variation_feature alt alleles were used which for a G/A/C/T variant is always A/C/T.
=> use correct transcript variation alt allele

Conservation.pm
Conservation plugin can't handle prefix 'chr' (#261).
=> Delete prefix 'chr' from chromosome

Conservation.pm
Conservation plugin can't handle prefix 'chr' (#261).
=> Delete prefix 'chr' from chromosome 98

CADD.pm
Bio/EnsEMBL/Variation/Utils/BaseVepTabixPlugin.pm::get_data throws an error if start is 0 (vep issue 678). I can reproduce the error with VCF formatted variant  '17 2 . N A id . .'. At the moment I don't know why we are subtracting 2 from the vf_start before passing it to get_data(). For now I'm only checking that the start doesn't get smaller than 1 which works. I need to apply that fix also to 98, 99 and postreleasefix/100.
=> check that vf start does not go below 1

StructuralVariantOverlap.pm
Issue #280 
There's a missing column in the output file when using option 'cols=AF'.
=> Fix SV overlap custom field

CADD.pm
The `get_matched_variant_alleles` takes into consideration the ref/alt and strand information. The removed line was redundant and only reversing the alt allele while the strand and ref allele were still the original values.
Test script and results before/after in PANDA/data/VEP_plugins/vep_CADD_grch38.sh
Example: 
rs183413880 (+ strand) and NM_181426.2:c.1073C>T (- strand) expected to retrieve same CADD scores as both notations refer to same variation.
=> Fix - CADD -1 strand

dbNSFP.pm
Support newer 4.x versions. I tested with version 4.1a(PANDA/anja/dbNSFP_tests/dbNSFP_4.1a_grch38.sh) and 4.0a(PANDA/anja/dbNSFP_tests/dbNSFP_4.0a_grch38.sh).
Longterm we need to clean up the logic for checking the version.
I will create a PR against postreleasefix/102 too.
=> support different 4.x versions

G2P.pm
Add missing key which is needed to find the VCFCollection for latest gnomAD v3 in vcf_config.json. I will add the same PRs for 101,102 and master.
=> add latest gnomADg_r3.0 key

PolyPhen_SIFT.pm
Fix for #321 
Create database only using PolyPhen and SIFT
Use only PolyPhen and SIFT from database - in case of use of already created database
Will do PR on release/101, release/102 and master after review on release/100
=> Restrict analyses to PolyPhen and SIFT - e100

neXtProt.pm
Fixes the "Experimental keys on scalar is now forbidden" compilation error on perl v5.26.1
=> Fix compilation error in neXtProt plugin for perl v5.26.1

plugin_config.txt
Adding the species fixes the plugin display in non-human species. 
ENSWEB-6073 
Sandbox: http://ves-hx2-76.ebi.ac.uk:7040/Homo_sapiens/Tools/VEP?db=core;tl=S0dJ89tbHAfoAxaH-341
=> DisGeNET add species

plugin_config.txt
The species info affects the web vep display. These two plugins should only be available for human. 
Sandbox: http://ves-hx2-76.ebi.ac.uk:7040/Homo_sapiens/Tools/VEP?db=core;tl=S0dJ89tbHAfoAxaH-341
=> Add species info to Mastermind and DisGeNET

gnomADc.pm
From #289, this PR describes how to use the gnomADc plugin with older releases of the coverage summary files including release 2.0.1 and 2.0.2.
=> Update gnomADc docs

SpliceAI.pm
The current structure in JSON, VEP and tab doesn't include the value name before the value which is confusing for REST users.
Example input: rs699
ENSVAR-3968
=> Change SpliceAI output

DisGeNET.pm
The current output structure is confusing. There's no way to associate the PMID with the scores because we have a different list for each: one list with all PMIDs, another with scores and so on.
Example input: rs699
ENSVAR-3968
=> Improve DisGeNET output

SpliceAI.pm
The output needs to take the gene into account and report the scores for the input variant gene. 
Issue reported #393
=> SpliceAI - take gene into account

G2P.pm
$transcript->{_gene_stable_id} stores the db primary accession as assigned by NCBI for RefSeq genes. $transcript->{_gene}->stable_id stores the stable id from the gene table as assigned by ensembl. Use the latter for consistency across the plugin when storing gene related data. I will create similar PRs for 101, 102 and 103. For 104 I will create a separate method get_gene_symbol_id to make it easier to control how the the gene_stable_id is retrieved. Test data and script are stored under PANDA/variation/G2P/test_data_pr_gene_symbol_id
ENSVAR-4054
=> use ensembl assigned stable_id

REVEL.pm
Newer version of REVEL also contains GRCh38 positions. Update the plugin to work with the new files, but also still support the older REVEL files.
Issue has been reported here #397
New files are under PANDA/data/REVEL/2020-feb
=> support latest REVEL files with grch38 positions

plugin_config.txt
dbNSFP failing in web vep because `bStatistic_rankscore` doesn't exist.
=> Update dbNSFP header

G2P.pm
G2P::variants_filtered_by_frequency_threshold used a different key (highest_frequencies) to look up frequencies than was used by G2P::store_highest_frequency (highest_frequency). This allowed variants to pass the frequency filter that actually shouldn't have passed.
Only the vep output is affected and not the TXT and HTML output files. The VEP output contains G2P_flag and G2P_complete results which shouldn't be in the output.
This PR
-- uses a single point for retrieving frequencies from G2P::highest_frequency, which was renamed from G2P::store_highest_frequency.
It can be tested with this script: VARIATION_PANDA/G2P/test_cases/scripts/vep_g2p_37_104_t7.sh
After the PR, there shouldn't be any G2P_flag and G2P_complete results in the VEP output file for the given input variant.
=> create get set method for highest_frequency

REVEL.pm
A quick fix for the user query https://github.com/Ensembl/VEP_plugins/issues/397 
New revel file version Bgzipped and tabixed file can be found in /nfs/production/panda/ensembl/variation/data/REVEL/2021-may
=> A quick fix for the REVEL plugin user query

dbNSFP.pm
This is a fix for #428 
For multi-allelic input values were not being returned with pep_match
Further information is in ENSVAR-4336
=> dbNSFP fix for multi-allelic and peptide matching

Downstream.pm
I'm not sure if this is really all that helpful, I hope that it is so I thought I'd submit a PR anyway. I refactored the Downstream plugin a few months ago but got busy with other projects. It removes the dependency on POSIX ceil and simplifies how the sequence "to translate" is obtained. In my limited testing, it produced the same results as the current version (v2.3). I found this PR helpful when I was debugging pVACtools (please see #342). I wonder if this could be helpful for you @at7?
=> Remove POSIX ceil dep from Downstream

CAPICE.pm, plugin_config.txt
**Ticket [ENSVAR-4463](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-44630)**
This plugin is developed based on the [CADD.pm](https://github.com/Ensembl/VEP_plugins/blob/release/105/CADD.pm) plugin with added safeguards to check if arguments are valid files.
@jamie-m-a, I did not include the filtering step as an input argument, but I do mention `filter_vep` it in the documentation. Is the documentation presented as is enough to describe the plugin?
Code used to test the plugin: https://github.com/nuno-agostinho/CAPICE-VEP-plugin-testing
=> Add CAPICE plugin

GO.pm
**Ticket [ENSVAR-4517](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4517)** to resolve the following issues: #37 and #445 
Based on [Phenotypes.pm](https://github.com/Ensembl/VEP_plugins/blob/release/107/Phenotypes.pm), the GO.pm plugin was improved to:
1. Check if there is a Tabix-indexed GFF file based on species, assembly and database version in a given path. The path can be provided as an optional parameter (by default, the working directory is used).
2. If a specific GFF file is not available, perform a SQL query in the Ensembl core database to retrieve GO terms per transcript and write results as a Tabix-indexed GFF file.
3. Read the Tabix-indexed GFF file to retrieve the GO terms per transcript.
For compatibility purposes, the plugin accepts a `remote` parameter in order to use …
=> Improve GO plugin: GRCh38 fix + offline mode support

EVE.pm, plugin_config.txt
JIRA Ticket: [here](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4502)
Confluence: [here](https://www.ebi.ac.uk/seqdb/confluence/pages/viewpage.action?spaceKey=EV&title=EVE+Plugin)
We are going to add [EVE data](https://evemodel.org/) as an easy-to-run plugin inside VEP. This data should add potential information to tag clinical relevant SNPs.  For more information, look at [publication](https://www.nature.com/articles/s41586-021-04043-8).
Just add --plugin flag with EVE + file, example:
`--plugin EVE,file=<PATH-TO>/eve_merged.vcf.gz`
Output should have EVE_SCORE + EVE_CLASS in output VCF.
=> feat: Add EVE Plugin

CADD.pm, plugin_config.txt
CADD plugin subroutine `parse_data()` uses a fixed header structures (6 columns). Therefore, it's not possible for similar CADD files to be used as input and possibly can introduce a few errors. Thereby, in this pull request, it was introduced a parsing directly on header names which should maintain old compatibility + introduce new possibilities.
1) Run CADD with a 6-column example with master + this branch and make sure output is the same.
2) Run CADD with different column structures (less and more than 6-column).
3) Run CADD with no columns that should be expected (no PHRED or RawScore).
3) Check if all new "die"s works properly and cover properly CADD.
* Ensembl-variation: [here](https://github.com/Ensembl/ensembl-variation/pull/788)
=> refactor: parse data with header + add specified file check 

LOVD.pm
[Ticket ENSVAR-4344](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4344) to solve the last issue reported in Ensembl/ensembl-vep#1041
When running LRG variants with the LOVD plugin, we get the following warnings for each LRG variant:
```
Use of uninitialized value $gene in join or string at /hps/software/users/ensembl/repositories/nuno/VEP_plugins/LOVD.pm line 114, <$__ANONIO__> line 3.
Use of uninitialized value $acc in join or string at /hps/software/users/ensembl/repositories/nuno/VEP_plugins/LOVD.pm line 114, <$__ANONIO__> line 3.
Use of uninitialized value $dna in join or string at /hps/software/users/ensembl/repositories/nuno/VEP_plugins/LOVD.pm line 114, <$__ANONIO__> line 3.
```
LOVD plugin queries the REST API of LOVD using the slice name, start and end for each variant, forming …
=> Support LRGs in LOVD plugin

dbNSFP.pm
Hello! Long time no pull-request 😸 !
This parameter when enabled forces multi-value fields in dbNSFP to
be split and correctly assigned by transcript ID as defined for the
current TranscriptVariationAllele object.
It is left off by default to prevent breaking others' downstream
processes and to mitigate for dbNSFP transcript versions being out
of sync with Ensembl/VEP.
=> Add optional transcript_match parameter to dbNSFP plugin

dbNSFP.pm
This PR is meant to add version used in dbNSFP Plugin header as mentioned in https://github.com/Ensembl/VEP_plugins/issues/474. Since dbNSFP version is only based on filename, I added full filename without `.gz` suffix to indicate which version was used in plugin.
1. Run VEP with `--plugin dbNSFP,/path-to/dbNSFP_file.gz,CADD_phred`
For example:
`--plugin dbNSFP,/many/directories/to/file/dbNSFP/4.3a/dbNSFP4.3a_grch38.gz,CADD_phred` should have
`##CADD_phred=(from dbNSFP4.3a_grch38)` as a header
=> feat: Include filename in dbNSFP header

MaxEntScan.pm, plugin_config.txt
Dataset website from MaxEntScan was updated to `http://hollywood.mit.edu/burgelab/maxent`. This PR is to change this URL in our documentation. PR based on issue https://github.com/Ensembl/VEP_plugins/issues/486.
1) Just click on new link and see it exists with necessary data from MaxEntScan.
=> fix: update maxentscan web

dbNSFP.pm
This PR solves some issues on this [PR ](https://github.com/Ensembl/VEP_plugins/pull/461 ) that added transcript_match feature for dbNSFP plugin. 
When enabled transcript_match feature matches transcript and give value from that specific transcript from dbNSFP files for transcript specific fields instead of giving value from all the transcripts which can be confusing.
This PR fixes - 
- some fields that are not transcript specific
- the plugin to go on even if a transcript specific field cannot be filtered and give result for other fields.
=> Fix some issues on dbNSFP transcript_match feature

GO.pm, plugin_config.txt
* Avoid error when assembly is not defined
* Avoid creating GFF file in REST
**Testing**: No GTF file should be created in REST mode.
----
* Replace commas followed by an underscore with `_-_`
* e.g., `GO:0045892:negative_regulation_of_transcription,_DNA-templated`
* Replace commas in other situations with `_`
* e.g., `GO:0016316:phosphatidylinositol-3,4-bisphosphate_4-phosphatase_activity`
* Replace spaces with underscore in Perl instead of SQL (for consistency with new changes)
Fixes issues with VCF output format where commas (usually only used to denote different entries) are replaced with `&`. Before this fix, VCF output could print the following for the GO terms: `GO:0045892:negative_regulation_of_transcription&_DNA-templated&GO:0005515:protein_binding`
**Testing:**
* Created GFF …
=> Improve GO plugin

EVE.pm
EVE plugin is not running in VEP REST due to absence of `config->assembly`. This PR is meant to fix this problem.
1) Run VEP in REST and make sure is still working in vep command-line.
=> fix: REST assembly config to EVE

REVEL.pm
Related with issue https://github.com/Ensembl/VEP_plugins/issues/518
When passing an undefined assembly (as it occurs if running VEP in offline mode), return a proper error informing the user to add argument `--assembly`:
```
specify assembly using --assembly [assembly]
```
Test VEP in offline mode with and without defining assembly for REVEL.pm:
```
vep -i input.vcf --offline --plugin REVEL,new_tabbed_revel_grch38.tsv.gz
vep -i input.vcf --offline --asembly GRCh38 --plugin REVEL,new_tabbed_revel_grch38.tsv.gz
```
=> Improve error message when running REVEL.pm with undefined assembly

StructuralVariantOverlap.pm
For some variants the seq_region_name is not defined, in those cases get the name from `$svf->{chr}`.
Issue raised in this ticket: https://github.com/Ensembl/VEP_plugins/issues/495
=> Get seq_region in StructuralVariantOverlap

G2P.pm
Check if $af_threshold is defined to avoid the following message:
`Use of uninitialized value $af_threshold in numeric le (<=) at /home/u035/u035/shared/software/bcbio/anaconda/share/ensembl-vep-100.4-0/G2P.pm line 653, <_ANONIO_> line 15403.`
Details: [ENSVAR-4804](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4804)
=> G2P check af_threshold is defined

mutfunc.pm, plugin_config.txt
Mutfunc website - http://www.mutfunc.com/help
Mutfunc have several analysis and corresponding output file for them. We have built the plugin for 4 of them - 
motif.tab - effects on linear motif
int.tab - effects on interaction 
mod.tab - effects on protein structure
exp.tab - effects on protein structure (experimental)
~~tfbs.tab - effects on transcription factor binding site~~ (removed due to mismatch in sequnence)
For the first 4 of them do not have genomic location and described with protein location informtaion. That is why we have built a SQLite database for them with similar fashion how we have our protein function table. So it has a single table `consequences (species, md5, item, matrix)` where we are storing a 2D matrix against each transcript md5 and each analysis.
(at first, I …
=> Adding mutfunc plugin

G2P.pm
The issue was raised in this ticket: https://github.com/Ensembl/ensembl-vep/issues/1249 
Tested with perl version 5.30
=> G2P - fix experimental keys

IntAct.pm
- Fix: some species like chicken RJF had gca in their name and it was failing taxonomy id lookup. So removed gca from species name.
- Improvement: we were exactly matching the HGVS description. For example, if from genomic location file we got a HGVS description like `p.Pro712Ala` we were looking for the exact same match from the data file. But instead, for this instance, the data file had `p.[Pro712Ala;Pro715Ala]` and the match failed. We are now allowing this match because the allele `p.[Pro712Ala;Pro715Ala]` at least contains the variant we are looking for irrespective of whatever the additional information that the data line contains.
=> Extend IntAct data matching

AncestralAllele.pm, Conservation.pm, ExAC.pm, FlagLRG.pm, IntAct.pm, LD.pm, MPC.pm, ReferenceQuality.pm, StructuralVariantOverlap.pm, mutfunc.pm, pLI.pm, plugin_config.txt
As part of migrating ftp links to be accessible over https, I've checked for ftp URLs accross all Ensembl repos.
This PR updates ftp URLs in this repo from http:// and ftp:// protocol to https.
The affected hostnames have been tested to work with https.
Other affected repos are listed in the JIRA ticket.
Webteam JIRA ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6632
Sandbox: http://wp-np2-1d.ebi.ac.uk:1680/
=> Update ftp links to https

Conservation.pm
The plugin reads file from the FTP using `ensembl-io` bigwig parser and with https link it fails to open it -
https://github.com/Ensembl/VEP_plugins/blob/70e472593e1d87d8269dae05fb97763b20818b35/Conservation.pm#L181
with error -
```
perl: symbol lookup error: /hps/software/users/ensembl/ensw/C8-MAR21-sandybridge/plenv/versions/5.14.4/lib/perl5/site_perl/5.14.4/x86_64-linux-thread-multi-ld/auto/Bio/DB/BigFile/BigFile.so: undefined symbol: SSL_library_init
```
It comes from the the `Bio::DB::BigFile`  dependency -
https://github.com/Ensembl/ensembl-io/blob/58d13c13180c04259093621cab192d5d4fafc7eb/modules/Bio/EnsEMBL/IO/BigFileParser.pm#L34 
Reverting back to http.
=> FTP with https links is causing error

config/cpanfile, config/requirements.txt, config/ubuntu-packages.txt
[ENSVAR-4574](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4574): Adding VEP plugins to docker image
This PR add three files to list the dependencies needed to run VEP plugins in VEP Docker image (excluding dependencies already installed for **ensembl-vep**):
* **config/cpanfile** for Perl packages
* **config/requirements.txt** for Python modules
* **config/ubuntu-packages.txt** for Ubuntu packages
These files are required for https://github.com/Ensembl/ensembl-vep/pull/1299
=> Add plugin dependencies to build VEP Docker image

plugin_config.txt
[ENSVAR-4536](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4536): given that the gnomAD data includes ExAC data (and this is now available through cache), this PR disables ExAC plugin for 109, including:
* No longer being available to install via `INSTALL.pl`
* Remove plugin documentation from [the public list of VEP plugins](https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html)
ExAC plugin code will be deprecated later for 110: [ENSVAR-5276](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5276)
=> Deprecate ExAC plugin (109)

plugin_config.txt
[ENSVAR-5227](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5227): the miRNA plugin has been superseded by the `--mirna` flag in VEP
=> Deprecate miRNA plugin

CADD.pm
Now we also have CADD SV data, this PR adjusts CADD original code to allow new details from SV input.
1) CADD SV have only 3 terms (INS, DEL and DUP);
2) `variation_feature_seq` was altered to `base_variation_feature`;
3) A variant_feature_type was added `StructuralVariationFeature`;
4) Match was tested with short variants and SVs.
5) Since `get_matched_variant_alleles` does not receive `end` as input, a conditional to skip non-matching `end` was added.
Files: https://kircherlab.bihealth.org/download/CADD-SV/v1.1/
1) Test with short variants reference file;
2) Test with SV reference;
3) Test with both.
=> feat: Allow SV data to CADD

plugin_config.txt
[ENSVAR-5227](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5227): Deprecated miRNA plugin should not be configured in plugin config
Redoing https://github.com/Ensembl/VEP_plugins/pull/555 that was reverted somehow
=> Remove deprecated miRNA plugin from plugin config

dbNSFP.pm, plugin_config.txt
[ENSVAR-5414](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5414), based on Ensembl/ensembl-rest#544
When using the dbNSFP plugin, the plugin dies if any of the fields is not available in the dbNSFP file. In the command-line, VEP still returns an output with a warning explaining which fields are invalid.
However, if using dbNSFP with an invalid field in REST, VEP returns its output with no dbNSFP fields. Given that REST does not display any warning messages, the user has no idea whether the plugin didn't return anything because that variant is not found in dbNSFP or if there is an invalid field. Related with **documentation update in REST**: Ensembl/ensembl-rest#581.
The following changes apply to the dbNSFP plugin in general and are not restricted to only REST.
- Print all fields even …
=> Improve dbNSFP plugin

REVEL.pm
By default, if the REVEL file contains transcript ids the plugin is going to return scores only if the transcripts match. 
This PR adds the option to not match by transcript id.
It also checks if alt alleles match.
Test case: https://github.com/Ensembl/ensembl-vep/issues/1369
=> Add option to REVEL

PON_P2.pm
Issue reported here https://github.com/Ensembl/VEP_plugins/issues/590 
The plugin doesn't need to fetch the chr, pos and alleles from the hgvs_genomic. It can directly fetch them from objects `$vf` and `$tva`.
Please see the ticket [ENSVAR-5546](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5546) for details on how to test.
=> Fix plugin PON_P2

CADD.pm, CAPICE.pm, ClinPred.pm, Mastermind.pm, PON_P2.pm, ProteinSeqs.pm, REVEL.pm
[ENSVAR-5551](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5551)
We need to be able to call multiple options using option names like `file = ,option1= , option2=` while still maintaining legacy for  reproducibility. 
This PR adds this feature. 
**Test can be done using all plugins affected.** 
_For example using REVEL and assembly GRCh37_
`--plugin REVEL,file=PATH_to_REVEL_file,no_match=1`
Test to check for old legacy 
`--plugin REVEL,PATH_to_REVEL_file,1`
=> Plugin changes to support multiple calls

CADD.pm, plugin_config.txt
Added non-commercial clause in CADD.
- in the hover over text in web VEP input form
- in hover over text in web VEP ouput
- in the CLI VEP header text
sandbox test url - 
http://wp-np2-11.ebi.ac.uk:7070/Homo_sapiens/Tools/VEP/Results?tl=s3J5sj9oRvhlosWw-158
=> Add non-commercial clause in CADD plugin

OpenTargets.pm, plugin_config.txt
[ENSVAR-5840](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5840)
[Open Targets Genetics](https://genetics.opentargets.org) is a comprehensive tool highlighting variant-centric statistical evidence to allow both prioritisation of candidate causal variants at GWAS loci. Their data includes locus-to-gene (L2G) scores that are useful to predict causal genes.
Plugin data location is described in [ENSVAR-5840](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5840).
Example VCF input:
```
11      436154  .       A       G       58      .       .
11      961268  .       TG      TGGAG   11.7169 .       .
11      1090036 .       T       C       30.4183 .       .
11      1140380 .       A       G       30.4183 .       .
20      851565  .       G       A       .       .       .
```
=> Open Targets Genetics plugin

dbNSFP.pm
Plugin throws warning:
`Use of uninitialized value in string ne at VEP_plugins/dbNSFP.pm line 356, <$__ANONIO__> line 1.`
**Input**
`3       12046077        12046077        C/A     +`
**Command**
--plugin dbNSFP,'consequence=ALL',dbNSFP4.3a_grch37.gz,LINSIGHT,LINSIGHT_rankscore,gnomAD_genomes_AF
=> Fix dbNSFP warning

EVE.pm, MaveDB.pm, PON_P2.pm, TranscriptAnnotator.pm
Replace smartmatch operator with equivalent functionality.
Smartmatch is an experimental feature that throws warnings in newer versions of Perl.
=> Avoid smartmatch operator

IntAct.pm, plugin_config.txt
We are intending to update IntAct plugin data to the latest published one -
[ENSVAR-5859](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5859)
Please also check - https://github.com/Ensembl/ensembl-rest_private/pull/135
- The new data file have change in how they represent allele in the `mutation_gc_map.txt` file - before, it was ref codon (e.g. - ATC) and now it is aa change (e.g. - G>S). Updated code to support that.
- Added new supported species - drosophila melanogaster
- Added all supported species to web/REST VEP too.
test_data - 
```
drosophila
3L	16039727	.	C	T
mouse 
2	127970880	.	A	G	.	.	.
4	43553083	.	C	G	.	.	.
```
command - 
```
vep --force_overwrite --plugin IntAct,mapping_file=data_0206/mutation_gc_map.txt.gz,mutation_file=data_0206/mutations.tsv --tab --species mus_musculus …
```
=> Intact - support new data format 

GO.pm
Fixes #622
May be related with Perl version used. Perl 5.34 returns the following warning: `WARNING: Failed to instantiate plugin GO: Modification of a read-only value attempted at /home/meryem/.vep/Plugins/GO.pm line 327`.
To avoid this issue, simply get a slice of `@$row` instead of using `splice()` that tries to modify the original array.
Try to create GO plugin data with: `./vep --id rs699 --database --plugin GO`
=> Fix read-only warning when creating GO data

plugin_config.txt
Currently, web VEP is hard-coded to consider all `Splicing predictions` as human-only (fixed in https://github.com/Ensembl/public-plugins/pull/716). This PR changes SpliceAI options to only appear for human in web VEP.
Test in [my sandbox](https://www.ensembl.org/Multi/Tools/VEP?db=core): SpliceAI options should only be available when human is selected.
=> Update SpliceAI plugin to be human-only

MaveDB.pm
[ENSVAR-5960](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5960): Ensure MaveDB VEP plugin works with regulatory data
This PR:
- skips the transcript matching if the MaveDB plugin data has no associated transcript (example: variants in regulatory regions, such as `NC_000023.11:g.139530529T>G`)
- increment 1 to end position to enable searching for insertions (such as `NC_000001.11:g.226361437_226361438insCGG`)
Please use the location of the MaveDB plugin data mentioned in the JIRA ticket, updated based on https://github.com/Ensembl/ensembl-variation/pull/1035 (110 data won't work for this variant).
```
NC_000023.11:g.139530529T>G
NC_000001.11:g.226361445_226361446delinsG
NC_000001.11:g.226361437_226361438insCGG
NC_000001.11:g.226361517_226361520del
NC_000001.11:g.226362048del
```
```bash …
```
=> MaveDB: return data for regulatory regions

AlphaMissense.pm
- Avoid smartmatch
- List valid columns on invalid input
- No smartwatch warning when using plugin with newer Perl versions:
```
vep --id rs201106962 --database --force \
--plugin AlphaMissense,file=AlphaMissense_hg38.tsv.gz,cols=am_genome:am_class
```
- Print list of available columns when asking for an invalid column:
```
vep --id rs201106962 --database --force \
--plugin AlphaMissense,file=AlphaMissense_hg38.tsv.gz,cols=am_genome:am_class:am_invalid_col
```
=> Avoid AlphaMissense smartmatch

MaveDB.pm
Resolves https://github.com/Ensembl/VEP_plugins/issues/669:
- Mention files are only available for GRCh38
- Add URL to download TBI files
=> Update MaveDB plugin data description

SpliceVault.pm, plugin_config.txt
ENSVAR-6077: SpliceVault predicts the precise nature of variant-associated mis-splicing
Please read the plugin description and check if its usage is clear. If not, ask me to improve it, thanks
**[UPDATED ON 28 NOV]** File path to SpliceVault data available in ENSVAR-6077
Example variants:
```
4 53458 . C G
8 232267 . G A
11 193107 . G T
14 18972751 . C G
20 95995 . T G
X 2789641 . C A
Y 2841627 . G C
```
<details><summary>Old example variants (older data)</summary>
<p>
```
4 59554 . T G
8 78907 . G A
11 1887471 . C T
14 18412137 . A G
20 145581 . A T
X 281484 . A G
Y 2787482 . T C
```
</p>
</details> 
Command-line example:
```
vep -i input.txt --plugin SpliceVault,file=splicevault_data.tsv.gz
```
=> Add SpliceVault plugin

PostGAP.pm, UTRAnnotator.pm, pLI.pm, satMutMPRA.pm
Sister PR in public plugins - https://github.com/Ensembl/public-plugins/pull/738
Updated some plugins Ensembl contact to match `author <email>` as doc generation script expects.
=> Add original author text for UTRannotator

RiboseqORFs.pm, plugin_config.txt
ENSVAR-5966: Re-calculate consequences of a variant/transcript pair based on ORF annotation from Havana.
The ORF data includes compatible transcripts with each ORF. If the current Ensembl transcript ID is not in the list, we skip it.
To get the consequences, we simply need to use the existing **VariationFeature** object and create a mock **Transcript** based on ORF features, where each **ORF block** is considered as an **exon**. We join both features in a new **TranscriptVariationAllele** object.
From this object, we calculate the variation consequences as usual in VEP. This will append the following data:
- `RiboseqORFs_consequences`: Recalculated consequences based on Ribo-seq ORF evidence
- `RiboseqORFs_id`: Ribo-seq ORF identifier
- `RiboseqORFs_impact`: Impact rating of the worst …
=> RiboseqORFs plugin

Paralogues.pm, plugin_config.txt
ENSVAR-2596
The Paralogues plugin fetches variants (from Ensembl API or custom VCF file) overlapping the genomic coordinates of amino acids aligned between paralogue proteins.
To check for variants in paralogue, this plugin:
1. [Creates a tabix-indexed TSV file with paralogue annotation (translations only) from Ensembl API](https://github.com/nuno-agostinho/VEP_plugins/blob/f1d6008a91ef67284ed53684e3a2cde306131e20/Paralogues.pm#L461), like so:
```
#homology_id    chr     start   end     strand  stable_id       version perc_cov        perc_id perc_pos        cigar_line      paralogue_chr   paralogue_start paralogue_end   paralogue_strand        paralogue_stable_id     paralogue_version       paralogue_cigar_line
1755604 1       65419   71585   1       ENSP00000493376 2       93.5583 92.638 …
```
=> Add paralogue variants plugin

UTRAnnotator.pm
Related with ENSVAR-5486
- Allow to annotate SVs with UTRAnnotator
- Add new argument `max_overlap`: maximum percentage of overlap between variant and UTR for UTR annotation
- Improve file download instructions
Some example variants to test with:
```
5  36876937 .  CC A    . . .
5  36876936 . .  <DEL> . . SVTYPE=DEL;END=36876939
18 13730626 . .  <DEL> . . SVTYPE=DEL;END=13730755
18 13730675 sv18 .  <DEL> . . SVTYPE=DEL;END=13730752
19 49453225 . .  <DEL> . . SVTYPE=DEL;END=49690898
19 49453225 . .  <DEL> . . SVTYPE=DEL;END=49695898
```
Test with different `max_overlap` values.
=> Annotate SV in UTRAnnotator

MaveDB.pm
Fixes #665
MaveDB is returning warnings when some MaveDB variants fall inside regulatory regions.
If the MaveDB variant has a transcript and/or protein associated, `RegulatoryFeature` and `MotifFeature` now simply return `0` when trying to check for its transcript/protein.
Test VEP using the MaveDB plugin with `--regulatory` enabled on the following set of variants: [test_github.zip](https://github.com/Ensembl/VEP_plugins/files/13828822/test_github.zip)
```
vep -i test_github.vcf \
--database \
--regulatory \
--plugin MaveDB,file=MaveDB_variants.tsv.gz
```
=> Fix MaveDB checks for RegulatoryFeature and MotifFeature

Phenotypes.pm
ENSVAR-3780: Avoid web VEP throwing error when using phenotypes on big SV
The SV `13 32307062 sv1 . <DEL> . . SVTYPE=DEL;END=32908738` was being annotated with 30k short variant-associated phenotypes for each transcript-variant pair, making the file too big to be handled by web VEP.
This coupled with using `--regulatory` in web VEP (default) would return the following crash error message, given that it would increase even more the big number of phenotypes in the file:
```
-------------------- EXCEPTION --------------------
MSG: 
ERROR: Forked process(es) died: read-through of cross-process communication detected
STACK Bio::EnsEMBL::VEP::Runner::_forked_buffer_to_output /hps/software/users/ensembl/repositories/nuno/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:562
STACK …
```
=> Avoid annotating SVs with short variant-associated phenotypes

CADD.pm
- prevent annotating SV variant if SNV and/or indels file is given as input parameters. User can still use `force_annotation=1`
- update description
=> CADD - more prevention of SV annotation with snv/indels annotation file

GeneSplicer.pm
Improves on https://github.com/Ensembl/ensembl-vep/pull/1599
- Accept `genesplicer` command instead of a path
- Works if `genesplicer` is exported in the `$PATH` variable (like in VEP Docker)
- Path to `genesplicer` is internally obtained via `which`
- Add key-value params to first two positional arguments:
- `binary` with `genesplicer` as default
- `training` with no default
- Improve plugin docs
- Add information on how to use GeneSplicer with VEP Docker/Singularity
If `genesplicer` is exported in the `$PATH` variable, like in VEP Docker/Singularity (https://github.com/Ensembl/ensembl-vep/pull/1599), there is no need to explicitly call it:
```
vep --id rs1348242192 --database --force --plugin GeneSplicer,training=${human_data}
```
This means that the only mandatory argument now is the …
=> GeneSplicer: improve argument processing

Downstream.pm
Ticket: [ENSVAR-3653](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-3653)
```
6   41903746    .   G   GG
6   41903746    .   GG  G
6   41903745    .   C   CA
```
```
vep --assembly GRCh37 --plugin Downstream
```
```
vep --assembly GRCh37 --hgvs --plugin Downstream
```
=> Fix to compute last complete codon in Downstream plugin

Conservation.pm
Ticket: ENSVAR-6144
User spotted issue with Conservation plugin not assigning GERP scores correctly for insertions and deletions when using the file option. More details in the ticket.
=> Fix del / ins error. Add MAX option

GWAS.pm
https://github.com/Ensembl/VEP_plugins/issues/684
- Added new option `quiet`. If `quiet=1` is given warnings are suppressed.
- Improved memory usage. Before the full curated file data was loaded into memory. Now we load only one line into memory at a time and print it into the "to be" processed file. This [curated file](https://www.ebi.ac.uk/gwas/api/search/downloads/alternative) took max ~200MB memory in the server.
- Improved run time for creating processed file. By default, we were querying Ensembl database to get variant information. This is more accurate but we also have this information in the given GWAS file. This [curated file](https://www.ebi.ac.uk/gwas/api/search/downloads/alternative) with >500k lines took 1.5 min in the server. Introduced new option `use_db` and when …
=> Improve and optimise GWAS plugin

RiboseqORFs.pm
* Throw error when running plugin in offline mode without FASTA file
* Throw warning when accessing Ensembl database instead of using FASTA file
=> Fix RiboseqORFs plugin without FASTA file

Phenotypes.pm
[ENSVAR-6264](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6264)
- `id_match`: The data from the file can return phenotype linked with overlapped variant and gene which we do not want. Added this option to optionally match against variant or gene identifiers. 
- `cols`: We can add more fields to the output using option, e.g. - `clinvar_clin_sig`. Before it was only `phenotype`, `source`, and `id`.
- if the output format is VCF replace `+` characters with `%2B`. Because `+` is used as delimiter for the phenotype fields in VCF output. 
Test:
```
vep --force --id  '1 942649 rs532223862 C G,T' --cache <cache dir> --offline --fasta <fasta> --cache_version 110 -a GRCh38 --plugin Phenotypes,file="<plugin dir>/Phenotypes_data_files/Phenotypes.pm_homo_sapiens_110_GRCh38.gvf.gz,id_match=1,cols=phe …
```
=> Phenotypes: add capability to id_match and adding cols to output

mutfunc.pm
The mutfunc plugin needs translation sequence for annotation. The VEP cache do not have the translation sequence. So, when `--offline` is used without a FASTA mutfunc do not annotate anything. Added a warning and skip any annotation logic altogether for such case.
```
vep -i <repo_dir>/ensembl-vep/examples/homo_sapiens_GRCh38.vcf --cache <cache_dir> --cache_version 112 -a GRCh38 --force --plugin mutfunc,db=<plugin data_dir>/mutfunc_data.db --offline
```
=> mutfunc: Skip annotation if no sequence

ClinPred.pm
ENSVAR-6395: Add ClinPred plugin for web/REST
When following the current instructions of ClinPred plugin, we get the following issue when trying to get data from chr20:
```bash
> tabix ClinPred_hg38_sorted_tabbed.tsv.gz 20 | head
[E::get_intv] Failed to parse TBX_GENERIC, was wrong -p [type] used?
The offending line was: "19	KI270938v1	19	54724028	G"
Reading "ClinPred_hg38_sorted_tabbed.tsv.gz" failed: No such file or directory
```
This occurs because the [original ClinPred file for GRCh38](https://sites.google.com/site/clinpred) includes invalid lines, such as:
```
1	KI270766v1	1	13109036	C
1	KI270766v1	1	13109036	C
1	KI270766v1	1	13109037	T
1	KI270766v1	1	13109037	T
1	KI270766v1	1	13109037	T
1	KI270766v1	1	13109038	C
1	KI270766v1	1	13109038	C
1	KI270766v1	1	13109040	A
1	KI270766v1	1 …
```
=> Fix ClinPred plugin data for GRCh38

PolyPhen_SIFT.pm, plugin_config.txt
ENSVAR-4600
* [**Create meta table in sqlite3 database**](https://github.com/Ensembl/VEP_plugins/commit/54a94cb17f9d0160e7850303c4e0e9a251dc1ea3)
* **Add SIFT/PPH2 plugin to public docs:** we are going to recommend users to use it when working with pangenome assemblies
1. Using a human MySQL database with a small number of protein function predictions (the full pangenomes database takes ~12h to produce the output), run VEP with PolyPhen_SIFT plugin with `create_db=1` and check if the `meta` table was copied to the sqlite database:
```bash
sqlite3 human_pangenomes.PolyPhen_SIFT.db 'select * from meta'
```
2. Check documentation update in [my sandbox](http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_plugins.html)
=> PolyPhen_SIFT plugin: add meta table to sqlite3 database

Conservation.pm
issue reported: https://github.com/Ensembl/VEP_plugins/issues/731
We should check for undef values in the parser.
```
vep --id "1 977935 . G A" --cache /path/to/tabixconverted --fasta /path/to/Homo_sapiens.GRCh38.dna.toplevel.fa.gz --force --cache_version 112 -a GRCh38 --offline --plugin Conservation,/path/to/gerp_conservation_scores.homo_sapiens.GRCh38.bw
```
=> Conservation: fix when there is no conservation data

UTRAnnotator.pm
https://github.com/Ensembl/VEP_plugins/issues/742
UTR object have start and end position as inclusive. So we should add 1 when calculating length.
Test:
```
10	97738477	rs3818876	G	A
```
=> Fix UTR length calculation

UTRAnnotator.pm
As per https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6428
Skipping UTR can result in incorrect CSQ calculation
=> rollback utr skip

Phenotypes.pm
The plugin reports overlapping phenotype features to the input features - it fetches the transcript and gene from the variation_feature. It doesn't make sense to include intergenic in this case.
This is a possible fix for this issue https://github.com/Ensembl/VEP_plugins/issues/753
=> Fix phenotypes plugin - remove intergenic from feature_types

SpliceAI.pm
For input:
`chr2 1542420 . GGA G . . .`
The plugin finds two matches:
2 1542420 . GGA G . . SpliceAI=G|TPO|0.92|0.89|0.00|0.00|3|1|-30|1 -> correct
2 1542421 . GAG G . . SpliceAI=G|TPO|0.00|0.00|0.00|0.00|0|3|-31|-45 -> incorrect
This PR changes the way the plugin matches the alleles.
Ticket: [ENSVAR-6407](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6407)
=> Fix SpliceAI alleles match

LOEUF.pm, pLI.pm
https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6429
gnomAD have published LOEUF data for GRCh38 in v4 release. The headers are different than what we had in v2. This PR allows both of them to be able to use with the plugin.
For pLI, only added a comment to say it is possible to use v4 data. The preparation step is similar, so we do not want to add another ~5M file in the repo.
Check the JIRA ticket
=> Allow gnomAD v4 data for LOEUF plugin

Downstream.pm
Ticket: [ENSVAR-6621](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6621)
```
vep -i input.vcf \
-o Result.vcf \
--assembly GRCh38 --no_stats --fork 4 --force \
--cache --offline --db_version 112 --use_given_ref \
--dir_cache <cache_dir> \
--fasta <fasta_file> \
--dir_plugins <plugins_dir> \
--vcf  \
--sift s --polyphen s --total_length --numbers \
--hgvs --protein --symbol --ccds --tsl --canonical  --mane --biotype \
--check_existing --exclude_null_alleles \
--cache_version 112 \
--plugin Downstream 
```
```
chr1    2430625 .   C   CGTGGGTGAGTGAGGCCCTGGCT
```
To check if there is no breaking change for other variants
=> Changed logic for calculating new peptide length

SpliceAI.pm
Ticket: [ENSVAR-6646](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6646)
- New option `split_output` to return each score in a different header (same as VCF output).
- Return the SpliceAI version in the header.
=> Update SpliceAI header and add output option

TSSDistance.pm
The default behaviour of the `TSSDistance` plugin is to annotate variants with 3' distance to transcripts. However often it is also of interest to know how far a variant is even if it is downstream to the transcription start site. This PR enrich this plugin with a feature to enable returning downstream distances as well if requested via a plugin parameter. This PR addresses issue #768 
**!Important to note**: the default behaviour of the plugin is unchanged. User has to provide extra parameter to invoke new feature.
=> feat: allowing downstream distances from TSS

PolyPhen_SIFT.pm
https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6567
Required in VEP in new infrastructure in absence of VEP cache.
Allow users to chose what score they want. Added following options - 
- `sift` - [p|s|b|o] works similarly as [--sift](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_sift) option in VEP. The value `o` turns off SIFT score/prediction.
- `polyphen` - [p|s|b|o] same as sift for PolyPhen humvar.
- `humdiv` - [p|s|b|o] same as sift for PolyPhen humdiv.
```
vep --id "1 230710048 . A G" --cache /nfs/production/flicek/ensembl/variation/data/VEP/tabixconverted --cache_version 113 --offline --force --plugin PolyPhen_SIFT,db=homo_sapiens.PolyPhen_SIFT.db,humdiv=b,polyphen=o -a GRCh38
```
Try using different permutation of the options.
=> Polyphen_SIFT: allow flexibility in choosing tools

Phenotypes.pm
This PR reverts https://github.com/Ensembl/VEP_plugins/pull/755
And fixes https://github.com/Ensembl/VEP_plugins/issues/753
Ticket: [ENSVAR-6767](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6767)
Test input:
```
13 105465961 105465961 C/T
19 1022782 1022782 A/G
X 20582587 20582587 T/TC
X 20304120 20304120 C/A
```
=> Re-introduce intergenic feature to Phenotypes plugin

SpliceAI.pm
JIRA ticket: [ENSVAR-6685](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6685) 
- Added to to the header section of SpliceAI.pm to explain in more detail to users how to download the Illumina files.
- Added a link to the Ensembl FTP data. 
- Also fixed reference to "...hg37.vcf.gz" > "...hg19.vcf.gz".
=> Add input file download instructions to SpliceAI header

SpliceVault.pm
[ENSVAR-6647](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6647)
=> Add location for hg19 SpliceVault assembly file

MaveDB.pm
There's overzealous protein/hgvs matching with current plugin. The wrong column was being used for matching if position is being used as part of the AA checking and a non-existent column was being used to instantiate a variable.
Tidied that up and seems to be working as intended, would appreciate some more extensive checks.
=> Fixing intended function

G2P.pm
Add options:
> [!NOTE]
> This update introduces a new column in the HTML report called `G2P variant consequence match`, when none of the options are run the column is populated with `NA`.
Also, improve documentation and fix URLs.
Ticket: [G2P-369](https://embl.atlassian.net/browse/G2P-369)
=> Add option to G2P to filter by variant consequence
